# https://pre-commit.com/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: "src/boost|src/zstr"
      - id: end-of-file-fixer
        exclude: "src/boost|src/zstr"
      - id: check-yaml
        exclude: "src/boost|src/zstr"
  # isort should run before black as black sometimes tweaks the isort output
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black"]
  # https://github.com/python/black#version-control-integration
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        # Copied from setup.cfg
        exclude: "properties|asv_bench|doc"
        additional_dependencies: [
            # Type stubs
            types-python-dateutil,
            types-pkg_resources,
            types-PyYAML,
            types-pytz,
            # Dependencies that are typed
            numpy,
            typing-extensions==3.10.0.0,
          ]
