channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - pandas>=1
  - numpy>=1.21
  - scipy>=1.6
  - xarray=0.19
  - bottleneck>=1.3.2
  - numexpr>=2.6.2
  - zarr>=2.3
  - dask>=2.11
  - matplotlib
  - ipython
  - sphinx-autosummary-accessors
  - sphinx_rtd_theme
  - nbsphinx
  - sphinxcontrib-programoutput
  - pytest
  - pytest-console-scripts
  - mypy
  - flake8
  - black
  - pre-commit
  - pip
  - setuptools>=45
  - wheel
  - pybind11>=2.6.0
  - setuptools_scm>=6.2
  - pip:
    - "git+https://bitbucket.org/biociphers/moccasin@new_moccasin"
    - "-e ."
