[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "pybind11>=2.6.0",
    "numpy>=1.14",
    "setuptools_scm>=6.2",
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/new_majiq/_version.py"
