package:
    name: majiq
    version: "{{ load_setup_py_data().version }}"

source:
    #git_tag: master
    #git_url: https://jordi_vaquero@bitbucket.org/biociphers/majiq.git
    path: /home/jordi/working/majiq

requirements:
    build:
        - python >= 3.3
        - jinja2
        - numpy
        - scipy
        - matplotlib
        - pysam
        - setuptools
        - cython
        - h5py
    run:
        - python >= 3.3
        - jinja2
        - numpy
        - scipy
        - matplotlib
        - pysam >= 0.8
        - setuptools
        - cython
        - h5py

build:
    preserve_egg_dir: True

    entry_points:
        - majiq = majiq.run_majiq:main
        - voila = voila.run_voila:main

about:
    home: http://www.biociphers.org
    license: GPL3
    summary: "MAJIQ"
